version: '3.8'

volumes:
  postgres:
  n8n:
  redis:
  openobserve:

x-n8n-shared: &n8n-shared
  restart: always
  image: n8nio/n8n:1.4.0
  env_file:
    - services/n8n/n8n-common.env
  links:
    - postgres
    - redis
  volumes:
    - n8n:/home/node/.n8n
    - ./services/n8n/creds:/data/creds
    - ./services/n8n/workflows:/data/workflows
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:11
    restart: always
    env_file: services/postgres/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./services/postgres/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    env_file: services/openobserve.env
    volumes:
      - openobserve:/data
    ports:
     - 5080:5080

  balancer:
    image: nginx:1.25.2
    env_file: services/balancer/nginx.env
    volumes:
      - ./services/balancer/default.conf:/etc/nginx/templates/default.conf.template
    ports:
      - "5679:80"

  n8n-main:
    <<: *n8n-shared
    environment:
      - INSTANCE_TYPE=main
    ports:
      - 5678:5678

  n8n-worker:
    <<: *n8n-shared
    environment:
      - INSTANCE_TYPE=worker
      - INSTANCE_NUM
    # Default worker concurrency is 10 
    # https://docs.n8n.io/hosting/scaling/queue-mode/#configure-worker-concurrency
    command: worker --concurrency=1 
    depends_on:
      - n8n-main
    profiles: ["replicated"]

  n8n-webhook:
    <<: *n8n-shared
    environment:
      - INSTANCE_TYPE=webhook
      - INSTANCE_NUM
    command: webhook
    depends_on:
      - n8n-main
    profiles: ["replicated"]

